services:

  postgres:
    container_name: postgresql
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${PGDATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./setup/scripts/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    networks:
      - app-network

  app:
    container_name: yapp-space
    build:
      context: .
    image: crudenesss/yapp-space
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - profile-picture-storage:/profile_pictures:rw
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  profile-picture-storage:
    driver: local
    name: profile-picture-storage
  postgres-data:
    driver: local
    name: postgres-data
